Lint/NoDisableComment:
  Enabled: true
  VersionAdded: "3.0.0"
  Description: "Checks for the use of `rubocop:disable` and `rubocop:todo` comments."
  AllowedCops: []

Lint/NoReturnInMemoization:
  Enabled: true
  VersionAdded: "3.0.0"
  Description: "Checks for the use of a `return` with a value in `begin..end` blocks in the context of instance variable assignment such as memoization."
